//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace familiasena.co.edu.sena.busdatos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="KactusSoap", Namespace="http://10.104.180.11")]
    public partial class Kactus : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Consulta_ContactoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Consulta_RegionalOperationCompleted;
        
        private System.Threading.SendOrPostCallback Consulta_DependenciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Consulta_PaisOperationCompleted;
        
        private System.Threading.SendOrPostCallback Consulta_DepartamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Consulta_MunicipioOperationCompleted;
        
        private System.Threading.SendOrPostCallback Consulta_FamiliaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Actualiza_FSenaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Kactus() {
            this.Url = global::familiasena.Properties.Settings.Default.familiasena_co_edu_sena_busdatos_Kactus;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Consulta_ContactoCompletedEventHandler Consulta_ContactoCompleted;
        
        /// <remarks/>
        public event Consulta_RegionalCompletedEventHandler Consulta_RegionalCompleted;
        
        /// <remarks/>
        public event Consulta_DependenciaCompletedEventHandler Consulta_DependenciaCompleted;
        
        /// <remarks/>
        public event Consulta_PaisCompletedEventHandler Consulta_PaisCompleted;
        
        /// <remarks/>
        public event Consulta_DepartamentoCompletedEventHandler Consulta_DepartamentoCompleted;
        
        /// <remarks/>
        public event Consulta_MunicipioCompletedEventHandler Consulta_MunicipioCompleted;
        
        /// <remarks/>
        public event Consulta_FamiliaCompletedEventHandler Consulta_FamiliaCompleted;
        
        /// <remarks/>
        public event Actualiza_FSenaCompletedEventHandler Actualiza_FSenaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.104.180.11/Consulta_Contacto", RequestNamespace="http://10.104.180.11", ResponseNamespace="http://10.104.180.11", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CRMInfoB[] Consulta_Contacto(string Operacion, string FechaInicio, string Fechafin, string CodAc) {
            object[] results = this.Invoke("Consulta_Contacto", new object[] {
                        Operacion,
                        FechaInicio,
                        Fechafin,
                        CodAc});
            return ((CRMInfoB[])(results[0]));
        }
        
        /// <remarks/>
        public void Consulta_ContactoAsync(string Operacion, string FechaInicio, string Fechafin, string CodAc) {
            this.Consulta_ContactoAsync(Operacion, FechaInicio, Fechafin, CodAc, null);
        }
        
        /// <remarks/>
        public void Consulta_ContactoAsync(string Operacion, string FechaInicio, string Fechafin, string CodAc, object userState) {
            if ((this.Consulta_ContactoOperationCompleted == null)) {
                this.Consulta_ContactoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsulta_ContactoOperationCompleted);
            }
            this.InvokeAsync("Consulta_Contacto", new object[] {
                        Operacion,
                        FechaInicio,
                        Fechafin,
                        CodAc}, this.Consulta_ContactoOperationCompleted, userState);
        }
        
        private void OnConsulta_ContactoOperationCompleted(object arg) {
            if ((this.Consulta_ContactoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Consulta_ContactoCompleted(this, new Consulta_ContactoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.104.180.11/Consulta_Regional", RequestNamespace="http://10.104.180.11", ResponseNamespace="http://10.104.180.11", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CRMRegion[] Consulta_Regional(string CodAc) {
            object[] results = this.Invoke("Consulta_Regional", new object[] {
                        CodAc});
            return ((CRMRegion[])(results[0]));
        }
        
        /// <remarks/>
        public void Consulta_RegionalAsync(string CodAc) {
            this.Consulta_RegionalAsync(CodAc, null);
        }
        
        /// <remarks/>
        public void Consulta_RegionalAsync(string CodAc, object userState) {
            if ((this.Consulta_RegionalOperationCompleted == null)) {
                this.Consulta_RegionalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsulta_RegionalOperationCompleted);
            }
            this.InvokeAsync("Consulta_Regional", new object[] {
                        CodAc}, this.Consulta_RegionalOperationCompleted, userState);
        }
        
        private void OnConsulta_RegionalOperationCompleted(object arg) {
            if ((this.Consulta_RegionalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Consulta_RegionalCompleted(this, new Consulta_RegionalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.104.180.11/Consulta_Dependencia", RequestNamespace="http://10.104.180.11", ResponseNamespace="http://10.104.180.11", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CRMDependencia[] Consulta_Dependencia(string CodAc) {
            object[] results = this.Invoke("Consulta_Dependencia", new object[] {
                        CodAc});
            return ((CRMDependencia[])(results[0]));
        }
        
        /// <remarks/>
        public void Consulta_DependenciaAsync(string CodAc) {
            this.Consulta_DependenciaAsync(CodAc, null);
        }
        
        /// <remarks/>
        public void Consulta_DependenciaAsync(string CodAc, object userState) {
            if ((this.Consulta_DependenciaOperationCompleted == null)) {
                this.Consulta_DependenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsulta_DependenciaOperationCompleted);
            }
            this.InvokeAsync("Consulta_Dependencia", new object[] {
                        CodAc}, this.Consulta_DependenciaOperationCompleted, userState);
        }
        
        private void OnConsulta_DependenciaOperationCompleted(object arg) {
            if ((this.Consulta_DependenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Consulta_DependenciaCompleted(this, new Consulta_DependenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.104.180.11/Consulta_Pais", RequestNamespace="http://10.104.180.11", ResponseNamespace="http://10.104.180.11", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CRMPais[] Consulta_Pais(string CodAc) {
            object[] results = this.Invoke("Consulta_Pais", new object[] {
                        CodAc});
            return ((CRMPais[])(results[0]));
        }
        
        /// <remarks/>
        public void Consulta_PaisAsync(string CodAc) {
            this.Consulta_PaisAsync(CodAc, null);
        }
        
        /// <remarks/>
        public void Consulta_PaisAsync(string CodAc, object userState) {
            if ((this.Consulta_PaisOperationCompleted == null)) {
                this.Consulta_PaisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsulta_PaisOperationCompleted);
            }
            this.InvokeAsync("Consulta_Pais", new object[] {
                        CodAc}, this.Consulta_PaisOperationCompleted, userState);
        }
        
        private void OnConsulta_PaisOperationCompleted(object arg) {
            if ((this.Consulta_PaisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Consulta_PaisCompleted(this, new Consulta_PaisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.104.180.11/Consulta_Departamento", RequestNamespace="http://10.104.180.11", ResponseNamespace="http://10.104.180.11", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CRMDpto[] Consulta_Departamento(string CodAc) {
            object[] results = this.Invoke("Consulta_Departamento", new object[] {
                        CodAc});
            return ((CRMDpto[])(results[0]));
        }
        
        /// <remarks/>
        public void Consulta_DepartamentoAsync(string CodAc) {
            this.Consulta_DepartamentoAsync(CodAc, null);
        }
        
        /// <remarks/>
        public void Consulta_DepartamentoAsync(string CodAc, object userState) {
            if ((this.Consulta_DepartamentoOperationCompleted == null)) {
                this.Consulta_DepartamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsulta_DepartamentoOperationCompleted);
            }
            this.InvokeAsync("Consulta_Departamento", new object[] {
                        CodAc}, this.Consulta_DepartamentoOperationCompleted, userState);
        }
        
        private void OnConsulta_DepartamentoOperationCompleted(object arg) {
            if ((this.Consulta_DepartamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Consulta_DepartamentoCompleted(this, new Consulta_DepartamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.104.180.11/Consulta_Municipio", RequestNamespace="http://10.104.180.11", ResponseNamespace="http://10.104.180.11", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CRMMunicipio[] Consulta_Municipio(string CodAc) {
            object[] results = this.Invoke("Consulta_Municipio", new object[] {
                        CodAc});
            return ((CRMMunicipio[])(results[0]));
        }
        
        /// <remarks/>
        public void Consulta_MunicipioAsync(string CodAc) {
            this.Consulta_MunicipioAsync(CodAc, null);
        }
        
        /// <remarks/>
        public void Consulta_MunicipioAsync(string CodAc, object userState) {
            if ((this.Consulta_MunicipioOperationCompleted == null)) {
                this.Consulta_MunicipioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsulta_MunicipioOperationCompleted);
            }
            this.InvokeAsync("Consulta_Municipio", new object[] {
                        CodAc}, this.Consulta_MunicipioOperationCompleted, userState);
        }
        
        private void OnConsulta_MunicipioOperationCompleted(object arg) {
            if ((this.Consulta_MunicipioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Consulta_MunicipioCompleted(this, new Consulta_MunicipioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.104.180.11/Consulta_Familia", RequestNamespace="http://10.104.180.11", ResponseNamespace="http://10.104.180.11", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsFamilia[] Consulta_Familia(string Cedula, string idfamiliar, string Correo, string CodAc) {
            object[] results = this.Invoke("Consulta_Familia", new object[] {
                        Cedula,
                        idfamiliar,
                        Correo,
                        CodAc});
            return ((ConsFamilia[])(results[0]));
        }
        
        /// <remarks/>
        public void Consulta_FamiliaAsync(string Cedula, string idfamiliar, string Correo, string CodAc) {
            this.Consulta_FamiliaAsync(Cedula, idfamiliar, Correo, CodAc, null);
        }
        
        /// <remarks/>
        public void Consulta_FamiliaAsync(string Cedula, string idfamiliar, string Correo, string CodAc, object userState) {
            if ((this.Consulta_FamiliaOperationCompleted == null)) {
                this.Consulta_FamiliaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsulta_FamiliaOperationCompleted);
            }
            this.InvokeAsync("Consulta_Familia", new object[] {
                        Cedula,
                        idfamiliar,
                        Correo,
                        CodAc}, this.Consulta_FamiliaOperationCompleted, userState);
        }
        
        private void OnConsulta_FamiliaOperationCompleted(object arg) {
            if ((this.Consulta_FamiliaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Consulta_FamiliaCompleted(this, new Consulta_FamiliaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.104.180.11/Actualiza_FSena", RequestNamespace="http://10.104.180.11", ResponseNamespace="http://10.104.180.11", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Actualiza_FSena(string COD_EMPL, string COD_FAMI, string TIP_RELA, string CONVOCATORIA, string CodAc) {
            object[] results = this.Invoke("Actualiza_FSena", new object[] {
                        COD_EMPL,
                        COD_FAMI,
                        TIP_RELA,
                        CONVOCATORIA,
                        CodAc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Actualiza_FSenaAsync(string COD_EMPL, string COD_FAMI, string TIP_RELA, string CONVOCATORIA, string CodAc) {
            this.Actualiza_FSenaAsync(COD_EMPL, COD_FAMI, TIP_RELA, CONVOCATORIA, CodAc, null);
        }
        
        /// <remarks/>
        public void Actualiza_FSenaAsync(string COD_EMPL, string COD_FAMI, string TIP_RELA, string CONVOCATORIA, string CodAc, object userState) {
            if ((this.Actualiza_FSenaOperationCompleted == null)) {
                this.Actualiza_FSenaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualiza_FSenaOperationCompleted);
            }
            this.InvokeAsync("Actualiza_FSena", new object[] {
                        COD_EMPL,
                        COD_FAMI,
                        TIP_RELA,
                        CONVOCATORIA,
                        CodAc}, this.Actualiza_FSenaOperationCompleted, userState);
        }
        
        private void OnActualiza_FSenaOperationCompleted(object arg) {
            if ((this.Actualiza_FSenaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Actualiza_FSenaCompleted(this, new Actualiza_FSenaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.104.180.11")]
    public partial class CRMInfoB {
        
        private string tIP_DOCUField;
        
        private string cEDULAField;
        
        private string nOMBRESField;
        
        private string aPELLIDOSField;
        
        private string gENEROField;
        
        private string pAI_RESIField;
        
        private string nPAI_RESIField;
        
        private string dTO_RESIField;
        
        private string mPI_RESIField;
        
        private string nMPI_RESIField;
        
        private string eEE_MAILField;
        
        private string tIPOEMPLField;
        
        private string nTIPOEMPLField;
        
        private string rEGIONALField;
        
        private string nREGIONALField;
        
        private string cENTROField;
        
        private string nCENTROField;
        
        private string fECHAMODField;
        
        private string eSTADOField;
        
        private string nro_RegistrosField;
        
        private string controlRField;
        
        /// <comentarios/>
        public string TIP_DOCU {
            get {
                return this.tIP_DOCUField;
            }
            set {
                this.tIP_DOCUField = value;
            }
        }
        
        /// <comentarios/>
        public string CEDULA {
            get {
                return this.cEDULAField;
            }
            set {
                this.cEDULAField = value;
            }
        }
        
        /// <comentarios/>
        public string NOMBRES {
            get {
                return this.nOMBRESField;
            }
            set {
                this.nOMBRESField = value;
            }
        }
        
        /// <comentarios/>
        public string APELLIDOS {
            get {
                return this.aPELLIDOSField;
            }
            set {
                this.aPELLIDOSField = value;
            }
        }
        
        /// <comentarios/>
        public string GENERO {
            get {
                return this.gENEROField;
            }
            set {
                this.gENEROField = value;
            }
        }
        
        /// <comentarios/>
        public string PAI_RESI {
            get {
                return this.pAI_RESIField;
            }
            set {
                this.pAI_RESIField = value;
            }
        }
        
        /// <comentarios/>
        public string NPAI_RESI {
            get {
                return this.nPAI_RESIField;
            }
            set {
                this.nPAI_RESIField = value;
            }
        }
        
        /// <comentarios/>
        public string DTO_RESI {
            get {
                return this.dTO_RESIField;
            }
            set {
                this.dTO_RESIField = value;
            }
        }
        
        /// <comentarios/>
        public string MPI_RESI {
            get {
                return this.mPI_RESIField;
            }
            set {
                this.mPI_RESIField = value;
            }
        }
        
        /// <comentarios/>
        public string NMPI_RESI {
            get {
                return this.nMPI_RESIField;
            }
            set {
                this.nMPI_RESIField = value;
            }
        }
        
        /// <comentarios/>
        public string EEE_MAIL {
            get {
                return this.eEE_MAILField;
            }
            set {
                this.eEE_MAILField = value;
            }
        }
        
        /// <comentarios/>
        public string TIPOEMPL {
            get {
                return this.tIPOEMPLField;
            }
            set {
                this.tIPOEMPLField = value;
            }
        }
        
        /// <comentarios/>
        public string NTIPOEMPL {
            get {
                return this.nTIPOEMPLField;
            }
            set {
                this.nTIPOEMPLField = value;
            }
        }
        
        /// <comentarios/>
        public string REGIONAL {
            get {
                return this.rEGIONALField;
            }
            set {
                this.rEGIONALField = value;
            }
        }
        
        /// <comentarios/>
        public string NREGIONAL {
            get {
                return this.nREGIONALField;
            }
            set {
                this.nREGIONALField = value;
            }
        }
        
        /// <comentarios/>
        public string CENTRO {
            get {
                return this.cENTROField;
            }
            set {
                this.cENTROField = value;
            }
        }
        
        /// <comentarios/>
        public string NCENTRO {
            get {
                return this.nCENTROField;
            }
            set {
                this.nCENTROField = value;
            }
        }
        
        /// <comentarios/>
        public string FECHAMOD {
            get {
                return this.fECHAMODField;
            }
            set {
                this.fECHAMODField = value;
            }
        }
        
        /// <comentarios/>
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
            }
        }
        
        /// <comentarios/>
        public string Nro_Registros {
            get {
                return this.nro_RegistrosField;
            }
            set {
                this.nro_RegistrosField = value;
            }
        }
        
        /// <comentarios/>
        public string ControlR {
            get {
                return this.controlRField;
            }
            set {
                this.controlRField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.104.180.11")]
    public partial class ConsFamilia {
        
        private string cOD_EMPLField;
        
        private string cOD_FAMIField;
        
        private string tIP_RELAField;
        
        private string eEE_MAILField;
        
        private string aPELLIDOSField;
        
        private string nOMBRESField;
        
        private string aPE_FAMIField;
        
        private string nOM_FAMIField;
        
        private string rELACIONField;
        
        private string nACIOField;
        
        private string eDADField;
        
        private string dEPENDEField;
        
        private string dISCAPField;
        
        private string rEGIONALField;
        
        private string cENTROField;
        
        private string aCTUALIZOField;
        
        private string nro_RegistrosField;
        
        private string controlRField;
        
        /// <comentarios/>
        public string COD_EMPL {
            get {
                return this.cOD_EMPLField;
            }
            set {
                this.cOD_EMPLField = value;
            }
        }
        
        /// <comentarios/>
        public string COD_FAMI {
            get {
                return this.cOD_FAMIField;
            }
            set {
                this.cOD_FAMIField = value;
            }
        }
        
        /// <comentarios/>
        public string TIP_RELA {
            get {
                return this.tIP_RELAField;
            }
            set {
                this.tIP_RELAField = value;
            }
        }
        
        /// <comentarios/>
        public string EEE_MAIL {
            get {
                return this.eEE_MAILField;
            }
            set {
                this.eEE_MAILField = value;
            }
        }
        
        /// <comentarios/>
        public string APELLIDOS {
            get {
                return this.aPELLIDOSField;
            }
            set {
                this.aPELLIDOSField = value;
            }
        }
        
        /// <comentarios/>
        public string NOMBRES {
            get {
                return this.nOMBRESField;
            }
            set {
                this.nOMBRESField = value;
            }
        }
        
        /// <comentarios/>
        public string APE_FAMI {
            get {
                return this.aPE_FAMIField;
            }
            set {
                this.aPE_FAMIField = value;
            }
        }
        
        /// <comentarios/>
        public string NOM_FAMI {
            get {
                return this.nOM_FAMIField;
            }
            set {
                this.nOM_FAMIField = value;
            }
        }
        
        /// <comentarios/>
        public string RELACION {
            get {
                return this.rELACIONField;
            }
            set {
                this.rELACIONField = value;
            }
        }
        
        /// <comentarios/>
        public string NACIO {
            get {
                return this.nACIOField;
            }
            set {
                this.nACIOField = value;
            }
        }
        
        /// <comentarios/>
        public string EDAD {
            get {
                return this.eDADField;
            }
            set {
                this.eDADField = value;
            }
        }
        
        /// <comentarios/>
        public string DEPENDE {
            get {
                return this.dEPENDEField;
            }
            set {
                this.dEPENDEField = value;
            }
        }
        
        /// <comentarios/>
        public string DISCAP {
            get {
                return this.dISCAPField;
            }
            set {
                this.dISCAPField = value;
            }
        }
        
        /// <comentarios/>
        public string REGIONAL {
            get {
                return this.rEGIONALField;
            }
            set {
                this.rEGIONALField = value;
            }
        }
        
        /// <comentarios/>
        public string CENTRO {
            get {
                return this.cENTROField;
            }
            set {
                this.cENTROField = value;
            }
        }
        
        /// <comentarios/>
        public string ACTUALIZO {
            get {
                return this.aCTUALIZOField;
            }
            set {
                this.aCTUALIZOField = value;
            }
        }
        
        /// <comentarios/>
        public string Nro_Registros {
            get {
                return this.nro_RegistrosField;
            }
            set {
                this.nro_RegistrosField = value;
            }
        }
        
        /// <comentarios/>
        public string ControlR {
            get {
                return this.controlRField;
            }
            set {
                this.controlRField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.104.180.11")]
    public partial class CRMMunicipio {
        
        private string cOD_MPIOField;
        
        private string nOM_MPIOField;
        
        private string cOD_DPTOField;
        
        private string nOM_DPTOField;
        
        private string cOD_PAISField;
        
        private string nOM_PAISField;
        
        private string nro_RegistrosField;
        
        private string controlRField;
        
        /// <comentarios/>
        public string COD_MPIO {
            get {
                return this.cOD_MPIOField;
            }
            set {
                this.cOD_MPIOField = value;
            }
        }
        
        /// <comentarios/>
        public string NOM_MPIO {
            get {
                return this.nOM_MPIOField;
            }
            set {
                this.nOM_MPIOField = value;
            }
        }
        
        /// <comentarios/>
        public string COD_DPTO {
            get {
                return this.cOD_DPTOField;
            }
            set {
                this.cOD_DPTOField = value;
            }
        }
        
        /// <comentarios/>
        public string NOM_DPTO {
            get {
                return this.nOM_DPTOField;
            }
            set {
                this.nOM_DPTOField = value;
            }
        }
        
        /// <comentarios/>
        public string COD_PAIS {
            get {
                return this.cOD_PAISField;
            }
            set {
                this.cOD_PAISField = value;
            }
        }
        
        /// <comentarios/>
        public string NOM_PAIS {
            get {
                return this.nOM_PAISField;
            }
            set {
                this.nOM_PAISField = value;
            }
        }
        
        /// <comentarios/>
        public string Nro_Registros {
            get {
                return this.nro_RegistrosField;
            }
            set {
                this.nro_RegistrosField = value;
            }
        }
        
        /// <comentarios/>
        public string ControlR {
            get {
                return this.controlRField;
            }
            set {
                this.controlRField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.104.180.11")]
    public partial class CRMDpto {
        
        private string cODPTOField;
        
        private string nCODPTOField;
        
        private string nro_RegistrosField;
        
        private string controlRField;
        
        /// <comentarios/>
        public string CODPTO {
            get {
                return this.cODPTOField;
            }
            set {
                this.cODPTOField = value;
            }
        }
        
        /// <comentarios/>
        public string NCODPTO {
            get {
                return this.nCODPTOField;
            }
            set {
                this.nCODPTOField = value;
            }
        }
        
        /// <comentarios/>
        public string Nro_Registros {
            get {
                return this.nro_RegistrosField;
            }
            set {
                this.nro_RegistrosField = value;
            }
        }
        
        /// <comentarios/>
        public string ControlR {
            get {
                return this.controlRField;
            }
            set {
                this.controlRField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.104.180.11")]
    public partial class CRMPais {
        
        private string cOD_PAISField;
        
        private string nOM_PAISField;
        
        private string nro_RegistrosField;
        
        private string controlRField;
        
        /// <comentarios/>
        public string COD_PAIS {
            get {
                return this.cOD_PAISField;
            }
            set {
                this.cOD_PAISField = value;
            }
        }
        
        /// <comentarios/>
        public string NOM_PAIS {
            get {
                return this.nOM_PAISField;
            }
            set {
                this.nOM_PAISField = value;
            }
        }
        
        /// <comentarios/>
        public string Nro_Registros {
            get {
                return this.nro_RegistrosField;
            }
            set {
                this.nro_RegistrosField = value;
            }
        }
        
        /// <comentarios/>
        public string ControlR {
            get {
                return this.controlRField;
            }
            set {
                this.controlRField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.104.180.11")]
    public partial class CRMDependencia {
        
        private string cODIGOField;
        
        private string nOMBREField;
        
        private string rEGIONALField;
        
        private string nREGIONALField;
        
        private string nro_RegistrosField;
        
        private string controlRField;
        
        /// <comentarios/>
        public string CODIGO {
            get {
                return this.cODIGOField;
            }
            set {
                this.cODIGOField = value;
            }
        }
        
        /// <comentarios/>
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
            }
        }
        
        /// <comentarios/>
        public string REGIONAL {
            get {
                return this.rEGIONALField;
            }
            set {
                this.rEGIONALField = value;
            }
        }
        
        /// <comentarios/>
        public string NREGIONAL {
            get {
                return this.nREGIONALField;
            }
            set {
                this.nREGIONALField = value;
            }
        }
        
        /// <comentarios/>
        public string Nro_Registros {
            get {
                return this.nro_RegistrosField;
            }
            set {
                this.nro_RegistrosField = value;
            }
        }
        
        /// <comentarios/>
        public string ControlR {
            get {
                return this.controlRField;
            }
            set {
                this.controlRField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.104.180.11")]
    public partial class CRMRegion {
        
        private string rEGIONALField;
        
        private string nREGIONALField;
        
        private string nro_RegistrosField;
        
        private string controlRField;
        
        /// <comentarios/>
        public string REGIONAL {
            get {
                return this.rEGIONALField;
            }
            set {
                this.rEGIONALField = value;
            }
        }
        
        /// <comentarios/>
        public string NREGIONAL {
            get {
                return this.nREGIONALField;
            }
            set {
                this.nREGIONALField = value;
            }
        }
        
        /// <comentarios/>
        public string Nro_Registros {
            get {
                return this.nro_RegistrosField;
            }
            set {
                this.nro_RegistrosField = value;
            }
        }
        
        /// <comentarios/>
        public string ControlR {
            get {
                return this.controlRField;
            }
            set {
                this.controlRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Consulta_ContactoCompletedEventHandler(object sender, Consulta_ContactoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Consulta_ContactoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Consulta_ContactoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CRMInfoB[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CRMInfoB[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Consulta_RegionalCompletedEventHandler(object sender, Consulta_RegionalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Consulta_RegionalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Consulta_RegionalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CRMRegion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CRMRegion[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Consulta_DependenciaCompletedEventHandler(object sender, Consulta_DependenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Consulta_DependenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Consulta_DependenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CRMDependencia[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CRMDependencia[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Consulta_PaisCompletedEventHandler(object sender, Consulta_PaisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Consulta_PaisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Consulta_PaisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CRMPais[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CRMPais[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Consulta_DepartamentoCompletedEventHandler(object sender, Consulta_DepartamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Consulta_DepartamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Consulta_DepartamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CRMDpto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CRMDpto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Consulta_MunicipioCompletedEventHandler(object sender, Consulta_MunicipioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Consulta_MunicipioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Consulta_MunicipioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CRMMunicipio[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CRMMunicipio[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Consulta_FamiliaCompletedEventHandler(object sender, Consulta_FamiliaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Consulta_FamiliaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Consulta_FamiliaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsFamilia[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsFamilia[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Actualiza_FSenaCompletedEventHandler(object sender, Actualiza_FSenaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Actualiza_FSenaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Actualiza_FSenaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591